In [79]:
from sklearn.datasets import load_iris

data = load_iris()
print(data)

features = data['data']
target = data['target']

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [80]:
from sklearn.preprocessing import OneHotEncoder

target = target.reshape(-1, 1) # make 2d

encoder = OneHotEncoder(sparse_output=False) # encode to work with model
target = encoder.fit_transform(target)

print(target)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0.

In [81]:
from sklearn.model_selection import train_test_split

trainFeatures, testFeatures, trainTarget, testTarget = train_test_split(features, target, train_size=0.8)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential([ # each item is a layer
    Dense(16, activation='relu', input_shape=(4, )), # 16 here is the amount of neurones(2^x), relu, 4-features, 1-target
    Dense(16, activation='relu'),
    Dense(3, activation='softmax') # 3 classification layer
])

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy']) # preparing model

model.fit(trainFeatures, trainTarget, epochs=50, batch_size=5, verbose=1, validation_split=0.1)
# epoch is the amount of revisions the model will take over the data
# model trains off of batches of 5 to be quicker
# verbose is whether logs are shown or not 0/1
# validation split - 0.1/10% of epochs are split to evaluate off of

Epoch 1/50


C:\Users\eyomi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.3333 - loss: 1.3898 - val_accuracy: 0.2500 - val_loss: 1.3130
Epoch 2/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.3333 - loss: 1.1694 - val_accuracy: 0.2500 - val_loss: 1.1387
Epoch 3/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.3333 - loss: 1.0569 - val_accuracy: 0.4167 - val_loss: 1.0221
Epoch 4/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6111 - loss: 0.9812 - val_accuracy: 0.9167 - val_loss: 0.9074
Epoch 5/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7037 - loss: 0.9201 - val_accuracy: 0.8333 - val_loss: 0.8817
Epoch 6/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8056 - loss: 0.8693 - val_accuracy: 1.0000 - val_loss: 0.8320
Epoch 7/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8611 - loss: 0.8225 - val_accuracy: 1.0000 - val_loss: 0.7871
Epoch 8/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8519 - loss: 0.7732 - val_accuracy: 1.0000 - val_loss: 0.7259
Ep

In [83]:
model.evaluate(testFeatures, testTarget) # check accuracy

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 1.0000 - loss: 0.1087


[0.10871587693691254, 1.0]

In [84]:
prediction = model.predict(testFeatures)
print(prediction)
print(len(prediction))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step
[[9.91977930e-01 8.01554695e-03 6.47325260e-06]
 [3.46178596e-04 1.01177953e-01 8.98475826e-01]
 [1.01062767e-02 6.76312387e-01 3.13581347e-01]
 [1.02711404e-02 9.48712051e-01 4.10167947e-02]
 [9.95368719e-01 4.63064201e-03 7.19421280e-07]
 [1.49016036e-02 8.74858797e-01 1.10239625e-01]
 [1.94368567e-02 9.23869550e-01 5.66935614e-02]
 [8.95434059e-03 7.73853779e-01 2.17191905e-01]
 [1.70243124e-03 1.93714306e-01 8.04583192e-01]
 [1.48153314e-02 7.93028057e-01 1.92156598e-01]
 [1.33758485e-02 8.73000085e-01 1.13624088e-01]
 [1.72259957e-02 7.91427970e-01 1.91345975e-01]
 [3.23660817e-04 1.09998576e-01 8.89677763e-01]
 [1.04399463e-02 9.06322241e-01 8.32378045e-02]
 [4.85760655e-04 1.02159500e-01 8.97354782e-01]
 [1.07467570e-03 1.69312164e-01 8.29613090e-01]
 [9.94327962e-01 5.67106716e-03 8.99878899e-07]
 [8.38121958e-03 7.25382149e-01 2.66236663e-01]
 [9.97571051e-01 2.42872676e-03 2.74894518e-07]
 [9.96033132e-01 3.96611169e-03 7.11950179e-07]
 [

In [85]:
import numpy as np

np.argmax(prediction, axis=1) # position of maximum values (prediction)

array([0, 2, 1, 1, 0, 1, 1, 1, 2, 1, 1, 1, 2, 1, 2, 2, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 2])

In [90]:
# Decision Tree --------------------------------------------------------------------

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

classifier = DecisionTreeClassifier()
classifier.fit(trainFeatures, trainTarget)

prediction = classifier.predict(testFeatures)

print(accuracy_score(prediction, testTarget))

1.0
