In [95]:
text = 'I will walk to the store'
print(text)

words = text.lower().split(' ')
words.sort()
print(words)

indexToWord = {}
index = 0
for word in words:
    indexToWord[index] = word
    index += 1
print(indexToWord)

wordToIndex = {}
index = 0
for word in words:
    wordToIndex[word] = index
    index += 1
print(wordToIndex)

I will walk to the store
['i', 'store', 'the', 'to', 'walk', 'will']
{0: 'i', 1: 'store', 2: 'the', 3: 'to', 4: 'walk', 5: 'will'}
{'i': 0, 'store': 1, 'the': 2, 'to': 3, 'walk': 4, 'will': 5}


In [96]:
indexText = []
for word in text.lower().split(' '):
    indexText.append(wordToIndex[word])

indexText

[0, 5, 4, 3, 2, 1]

In [97]:
sequenceLength = 4

features = []
targets = []

for i in range(len(indexText)-sequenceLength):
    features.append(indexText[i:i+sequenceLength])
    targets.append(indexText[i+sequenceLength])

print(features)
print(targets)

[[0, 5, 4, 3], [5, 4, 3, 2]]
[2, 1]


In [98]:
import numpy as np

features = np.array(features)
targets = np.array(targets)

print(features.shape)

featuresCat = np.zeros((features.shape[0], features.shape[1], len(words))) # features shape, categories
featuresCat

(2, 4)


array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])

In [99]:
lisIndex = 0

for lis in features:
    itemIndex = 0
    for item in lis:
        featuresCat[lisIndex][itemIndex][item] = 1
        itemIndex += 1
    lisIndex += 1

featuresCat

array([[[1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 1., 0., 0.]],

       [[0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 1., 0., 0., 0.]]])

In [100]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, SimpleRNN

model = Sequential([
    SimpleRNN(128, input_shape=(sequenceLength, len(words)), activation='relu'), # neurones, input shape (sequence length, amount of unique words)
    Dense(len(words), activation='softmax')
])

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy']) # target is the actual value - not a class
model.fit(featuresCat, targets, epochs=50, batch_size=32, verbose=True)

Epoch 1/50


C:\Users\eyomi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.0000e+00 - loss: 1.9093
Epoch 2/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.0000e+00 - loss: 1.7921
Epoch 3/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.0000e+00 - loss: 1.6841
Epoch 4/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5000 - loss: 1.5866
Epoch 5/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 1.0000 - loss: 1.4904
Epoch 6/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 1.0000 - loss: 1.3979
Epoch 7/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 1.0000 - loss: 1.3058
Epoch 8/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 1.0000 - loss: 1.2189
Epoch 9/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 1.0000 - loss: 1.1341
Epoch 10/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 1.0000 - loss: 1.0496
Epoch 11/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 1.0000 - loss: 0.9655
Epoch 12/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 1.0000 - loss: 0.8806
Ep

In [104]:
def preprocess(tex):
    texIndex = []

    newWords = tex.lower().split(' ')

    newWords = newWords[-sequenceLength:]

    for word in words:
        texIndex.append(wordToIndex[word])

    texCat = np.zeros((1, sequenceLength, len(words)))

    itemIndex = 0
    for i in range(sequenceLength):
        texCat[0][i][texIndex[i]] = 1

    return texCat

preprocess('I will walk to')

array([[[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.]]])

In [105]:
prediction = model.predict(preprocess('I will'))
prediction = np.argmax(prediction)
prediction = indexToWord[prediction]
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step


'the'