In [57]:
text = """"When I went to the cinema to see this film, my first thought was, "Wow, this looks really good, I'm sure I'll love it," but in the end, it didn't quite live up to my expectations. 
Don't get me wrong, I liked it and found it quite enjoyable, but there were just a few things I found unpleasant, and I wanted to point them out. 
To begin, let's talk about the good points: The animation is very good. 
I saw many people saying that it looked better than Spider-Verse (another Sony film, the studio that made this one), but I personally prefer the animation in Spider-Verse to this film's, although I still think it's outstandingly good in this aspect. 
On the other hand, I also have to point out that there were certain moments that were genuinely funny. 
There were some jokes that only made the children in the cinema laugh, but there were also many parts where I couldn't stop laughing. 
That pleasantly surprised me. 
Another important point is that the action in the matches is very good and frenetic; I really enjoyed watching the few matches that could be seen in detail, but at the same time I feel that this has worked against it a bit, because, as I've already mentioned, there are very few fights that can be seen in detail in this film, and it seems like more are needed. 
Something I liked at first, but which later deteriorated, is that the pacing was very dynamic; in fact, it was too much so. The film starts by jumping from one thing to another quite effectively. 
They begin a scene, finish it properly, and move on to something else, but at a certain point, they start overusing editing to speed things up, omitting scenes that could have been very interesting for the viewer (I mention again some matches that last only seconds on screen as an example of this) and proceed to resolve the interpersonal conflicts that arise in the story in a matter of seconds. 
I feel that, because of all this, the film could have benefited from an extra 10 minutes. In conclusion, Goat is a very fun and entertaining film, but in its quest to keep your brain releasing dopamine, it leaves out many things that would have been very welcome."""

print(text)


"When I went to the cinema to see this film, my first thought was, "Wow, this looks really good, I'm sure I'll love it," but in the end, it didn't quite live up to my expectations. 
Don't get me wrong, I liked it and found it quite enjoyable, but there were just a few things I found unpleasant, and I wanted to point them out. 
To begin, let's talk about the good points: The animation is very good. 
I saw many people saying that it looked better than Spider-Verse (another Sony film, the studio that made this one), but I personally prefer the animation in Spider-Verse to this film's, although I still think it's outstandingly good in this aspect. 
On the other hand, I also have to point out that there were certain moments that were genuinely funny. 
There were some jokes that only made the children in the cinema laugh, but there were also many parts where I couldn't stop laughing. 
That pleasantly surprised me. 
Another important point is that the action in the matches is very good and fr

Extractive summary ---

In [58]:
import nltk # natural language toolkit
from nltk import sent_tokenize
nltk.download('punkt_tab')

from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\eyomi\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\eyomi\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [59]:
import regex

newText = sent_tokenize(text) # each sentence is a token
newText

['"When I went to the cinema to see this film, my first thought was, "Wow, this looks really good, I\'m sure I\'ll love it," but in the end, it didn\'t quite live up to my expectations.',
 "Don't get me wrong, I liked it and found it quite enjoyable, but there were just a few things I found unpleasant, and I wanted to point them out.",
 "To begin, let's talk about the good points: The animation is very good.",
 "I saw many people saying that it looked better than Spider-Verse (another Sony film, the studio that made this one), but I personally prefer the animation in Spider-Verse to this film's, although I still think it's outstandingly good in this aspect.",
 'On the other hand, I also have to point out that there were certain moments that were genuinely funny.',
 "There were some jokes that only made the children in the cinema laugh, but there were also many parts where I couldn't stop laughing.",
 'That pleasantly surprised me.',
 "Another important point is that the action in the m

In [60]:
cleanText = []

for sent in newText:
    sent = regex.sub(r"[^\w\s]", "", sent) # substitute *except* characters and spaces with ""
    sent = sent.lower()
    cleanText.append(sent)

cleanText

['when i went to the cinema to see this film my first thought was wow this looks really good im sure ill love it but in the end it didnt quite live up to my expectations',
 'dont get me wrong i liked it and found it quite enjoyable but there were just a few things i found unpleasant and i wanted to point them out',
 'to begin lets talk about the good points the animation is very good',
 'i saw many people saying that it looked better than spiderverse another sony film the studio that made this one but i personally prefer the animation in spiderverse to this films although i still think its outstandingly good in this aspect',
 'on the other hand i also have to point out that there were certain moments that were genuinely funny',
 'there were some jokes that only made the children in the cinema laugh but there were also many parts where i couldnt stop laughing',
 'that pleasantly surprised me',
 'another important point is that the action in the matches is very good and frenetic i really

In [61]:
tempText = []

for sent in cleanText:
    words = sent.split(' ')
    sent = []
    for word in words:
        if not word in stopwords.words('english'):
            sent.append(word)
    tempText.append(sent)

cleanText = tempText
cleanText # 2d list of sentences and words within

[['went',
  'cinema',
  'see',
  'film',
  'first',
  'thought',
  'wow',
  'looks',
  'really',
  'good',
  'im',
  'sure',
  'ill',
  'love',
  'end',
  'didnt',
  'quite',
  'live',
  'expectations'],
 ['dont',
  'get',
  'wrong',
  'liked',
  'found',
  'quite',
  'enjoyable',
  'things',
  'found',
  'unpleasant',
  'wanted',
  'point'],
 ['begin', 'lets', 'talk', 'good', 'points', 'animation', 'good'],
 ['saw',
  'many',
  'people',
  'saying',
  'looked',
  'better',
  'spiderverse',
  'another',
  'sony',
  'film',
  'studio',
  'made',
  'one',
  'personally',
  'prefer',
  'animation',
  'spiderverse',
  'films',
  'although',
  'still',
  'think',
  'outstandingly',
  'good',
  'aspect'],
 ['hand', 'also', 'point', 'certain', 'moments', 'genuinely', 'funny'],
 ['jokes',
  'made',
  'children',
  'cinema',
  'laugh',
  'also',
  'many',
  'parts',
  'couldnt',
  'stop',
  'laughing'],
 ['pleasantly', 'surprised'],
 ['another',
  'important',
  'point',
  'action',
  'matches'

In [62]:
from gensim.models import Word2Vec # word embeding -> words are converted to vectors, related words have similar vectors

embedder = Word2Vec(cleanText, vector_size=1, min_count=1, epochs=100)

In [63]:
embedder.wv # embeder.wv is a list of vectors that correspond to words

vectors = []

for i in range(len(cleanText)):
    vectors.append([])
    for j in range(len(cleanText[i])):
        vectors[i].append(embedder.wv[cleanText[i][j]])

vectors

[[array([1.2944868], dtype=float32),
  array([0.71921813], dtype=float32),
  array([1.6102256], dtype=float32),
  array([1.2789456], dtype=float32),
  array([1.521939], dtype=float32),
  array([1.8614447], dtype=float32),
  array([1.5101466], dtype=float32),
  array([1.6106807], dtype=float32),
  array([1.1673334], dtype=float32),
  array([1.0821068], dtype=float32),
  array([1.1390117], dtype=float32),
  array([1.3867669], dtype=float32),
  array([0.56873316], dtype=float32),
  array([0.7115676], dtype=float32),
  array([0.32778907], dtype=float32),
  array([1.751378], dtype=float32),
  array([0.48593998], dtype=float32),
  array([1.3668718], dtype=float32),
  array([0.33153665], dtype=float32)],
 [array([0.9197768], dtype=float32),
  array([0.09786563], dtype=float32),
  array([0.9318525], dtype=float32),
  array([1.5356283], dtype=float32),
  array([1.2638309], dtype=float32),
  array([0.48593998], dtype=float32),
  array([1.3844008], dtype=float32),
  array([2.0629852], dtype=float

In [64]:
longestLen = 0

for sent in cleanText:
    if len(sent) > longestLen:
        longestLen = len(sent)

longestLen

33

In [65]:
lens = []

for sent in cleanText:
    lens.append(len(sent))
print(max(lens)) # another method of ^

33


In [66]:
import numpy as np
# padding -> making all sentences same lenght as the longest

tempVectors = []

for sent in vectors:
    sent = np.pad(sent, (0, longestLen-len(sent))) # padding with 0s
    tempVectors.append(sent)

vectors = tempVectors
vectors

[array([[1.2944868 , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ],
        [0.71921813, 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ],
        [1.6102256 , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ],
        [1.2789456 , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ],
        [1.521939  , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.       